name: Generator
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '*'
jobs:
  generator-jhipster-entando:
    name: npm-test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm link
      - run: npm run test
        if: >-
          !contains(github.event.head_commit.message, '[skip ci]') &&
          !contains(github.event.pull_request.title, '[skip ci]') &&
          github.event.pull_request.draft == false
